export const ADD_MOVIES = "ADD_MOVIES";
export const FETCH_MOVIES = "FETCH_MOVIES";
export const FETCH_SUCEEDED = "FETCH_SUCEEDED";
export const FETCH_FAILED = "FETCH_FAILED";
export const UPDATE_MOVIE = "UPDATE_MOVIE";
export const UPDATE_SUCEEDED="UPDATE_SUCEEDED ";